<a href="https://colab.research.google.com/github/Agtna/AI-2025/blob/main/Jobsheet_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import pandas as pd
import datetime as dt

## Data Understanding
- Load dataset
---

In [13]:
# Customers

df_customers= pd.read_csv('./customers.csv')
df_customers

       CustomerID Segment Currency
0               3     SME      EUR
1               5     LAM      EUR
2               6     SME      EUR
3               7     LAM      EUR
4               9     SME      EUR
...           ...     ...      ...
32456       53307     SME      CZK
32457       53309     SME      CZK
32458       53311     SME      CZK
32459       53313     SME      CZK
32460       53314     SME      CZK

[32461 rows x 3 columns]

In [14]:
# Gas Stations

df_gasstations = pd.read_csv('./gasstations.csv')
df_gasstations

      GasStationID  ChainID Country          Segment
0               44       13     CZE  Value for money
1               45        6     CZE          Premium
2               46       23     CZE            Other
3               47       33     CZE          Premium
4               48        4     CZE          Premium
...            ...      ...     ...              ...
5711          5768        3     CZE            Other
5712          5769      153     SVK            Other
5713          5770        6     CZE          Premium
5714          5771        2     CZE           Noname
5715          5772       16     CZE            Other

[5716 rows x 4 columns]

In [15]:
# Products

df_products = pd.read_csv('./products.csv')
df_products

     ProductID                      Description
0            1                     Rucní zadání
1            2                            Nafta
2            3                          Special
3            4                            Super
4            5                          Natural
..         ...                              ...
586        602                              CNG
587        603                     Ethanol E-85
588        604                Zprostredk.nakupu
589        605      Replacement of UTA MultiBox
590        630  CCS Carnet Pronájem HW (Manual)

[591 rows x 2 columns]

In [16]:
# Transactions

df_transactions = pd.read_csv('./transactions_1k.csv')
df_transactions

,TransactionID,Date,Time,CustomerID,CardID,GasStationID,ProductID,Amount,Price
0,1,2012-08-24,09:41:00,31543,486621,3704,2,28,672.64
1,2,2012-08-24,10:03:00,46707,550134,3704,2,18,430.72
2,3,2012-08-24,10:03:00,46707,550134,3704,23,1,121.99
3,4,2012-08-24,13:53:00,7654,684220,656,5,5,120.74
4,5,2012-08-24,08:49:00,17373,536109,741,2,28,645.05
...,...,...,...,...,...,...,...,...,...
995,996,2012-08-26,13:04:00,12021,692529,3750,2,27,612.86
996,997,2012-08-26,11:52:00,15618,602037,438,2,29,635.22
997,998,2012-08-26,12:31:00,47057,533108,438,2,14,302.34
998,999,2012-08-25,07:51:00,22994,602354,3899,2,23,522.21
999,1000,2012-08-25,12:45:00,25986,655214,3899,2,38,870.93

In [17]:
# Year Month

df_yearmonth = pd.read_csv('./yearmonth.csv')
df_yearmonth

        CustomerID      Date  Consumption
0                5  201207.0       528.30
1                5  201302.0      1598.28
2                5  201303.0      1931.36
3                5  201304.0      1497.14
4                6  201203.0        51.06
...            ...       ...          ...
155713       21364  201203.0       800.29
155714       21364  201204.0       557.27
155715       21364  201205.0      1368.04
155716       21364  201206.0       729.24
155717          21       NaN          NaN

[155718 rows x 3 columns]

## Data Understanding
- Preview dataset
---

In [18]:
df_customer = pd.read_csv('customers.csv')
df_customer.head()

   CustomerID Segment Currency
0           3     SME      EUR
1           5     LAM      EUR
2           6     SME      EUR
3           7     LAM      EUR
4           9     SME      EUR

In [19]:
df_gasstations = pd.read_csv('gasstations.csv')
df_gasstations.head()

   GasStationID  ChainID Country          Segment
0            44       13     CZE  Value for money
1            45        6     CZE          Premium
2            46       23     CZE            Other
3            47       33     CZE          Premium
4            48        4     CZE          Premium

In [20]:
df_products = pd.read_csv('products.csv')
df_products.head()

   ProductID   Description
0          1  Rucní zadání
1          2         Nafta
2          3       Special
3          4         Super
4          5       Natural

In [21]:
df_transactions = pd.read_csv('transactions_1k.csv')
df_transactions.head()

,TransactionID,Date,Time,CustomerID,CardID,GasStationID,ProductID,Amount,Price
0,1,2012-08-24,09:41:00,31543,486621,3704,2,28,672.64
1,2,2012-08-24,10:03:00,46707,550134,3704,2,18,430.72
2,3,2012-08-24,10:03:00,46707,550134,3704,23,1,121.99
3,4,2012-08-24,13:53:00,7654,684220,656,5,5,120.74
4,5,2012-08-24,08:49:00,17373,536109,741,2,28,645.05

## Data Understanding
- Merge tables
---

In [22]:
df_merge1 = pd.merge(df_transactions, df_customers, on='CustomerID', how='left')
df_merge2 = pd.merge(df_merge1, df_gasstations, on='GasStationID', how='left')
df_merged = pd.merge(df_merge2, df_products, on='ProductID', how='left')

df_merged.head()

,TransactionID,Date,Time,CustomerID,CardID,GasStationID,ProductID,Amount,Price,Segment_x,Currency,ChainID,Country,Segment_y,Description
0,1,2012-08-24,09:41:00,31543,486621,3704,2,28,672.64,KAM,CZK,4,CZE,Premium,Nafta
1,2,2012-08-24,10:03:00,46707,550134,3704,2,18,430.72,KAM,CZK,4,CZE,Premium,Nafta
2,3,2012-08-24,10:03:00,46707,550134,3704,23,1,121.99,KAM,CZK,4,CZE,Premium,Provoz.nápl.
3,4,2012-08-24,13:53:00,7654,684220,656,5,5,120.74,KAM,CZK,30,CZE,Noname,Natural
4,5,2012-08-24,08:49:00,17373,536109,741,2,28,645.05,KAM,CZK,2,CZE,Noname,Nafta

## Data Understanding
- Preview Data types
---

In [23]:
df_merged.dtypes

TransactionID      int64
Date              object
Time              object
CustomerID         int64
CardID             int64
GasStationID       int64
ProductID          int64
Amount             int64
Price            float64
Segment_x         object
Currency          object
ChainID            int64
Country           object
Segment_y         object
Description       object
dtype: object

## Soal-1
Buatlah table list Top 5 Customers yang memiliki nilai transaksi paling banyak
---

## Soal-2
Buatlah list Top 5 Gas stations yang memiliki nilai transaksi paling banyak
---

In [24]:
df_gasstations = df_merged.groupby('GasStationID')
df_top5_station = df_gasstations[['Amount', 'Price']].sum()
df_top5_station.rename(columns={'Price':'Gas Sales'}, inplace=True)
df_top5_station.sort_values(by='Gas Sales', ascending=False).head()

              Amount  Gas Sales
GasStationID
4347             370    8557.94
48               295    6868.67
3250             320    6744.47
1155             292    6701.69
2417             273    6065.16

## Soal-3
Buatlah list Top 5 Jenis produk yang memiliki nilai transaksi paling banyak
---

In [25]:
df_products = df_merged.groupby('Description')
df_top5_product = df_products[['Amount', 'Price']].sum()
df_top5_product.rename(columns={'Price':'Sales'}, inplace=True)
df_top5_product.sort_values(by='Sales', ascending=False).head()

             Amount      Sales
Description
Nafta         15230  345669.45
Diesel +       1120   27261.03
Natural        1045   24639.46
Nafta Plus      317    7233.72
Natural +       157    3999.92

## Soal-4
Buatlah deskripsi statistik untuk masing masing hari (23,24,25,26) pada dataset transaction_1k
---

In [26]:
df = df_transactions.copy()
df['Date'] = pd.to_datetime(df['Date'])
df['Date'] = df['Date'].dt.day
filtered_df = df[df['Date'].isin([23, 24, 25, 26])]
daily_stats= filtered_df.groupby('Date')[['Amount', 'Price']].describe()
daily_stats

     Amount                                                        Price  \
      count       mean        std  min    25%   50%    75%    max  count
Date
23     10.0  29.600000  24.900692  1.0  21.25  26.5  35.25   91.0   10.0
24    492.0  19.936992  21.949630  0.0   5.00  19.0  27.00  264.0  492.0
25    425.0  18.880000  20.376114  0.0   4.00  17.0  26.00  154.0  425.0
26     73.0  21.219178  18.932810  0.0   6.00  20.0  29.00  101.0   73.0


            mean         std    min      25%     50%      75%      max
Date
23    685.379000  534.046487  76.42  481.170  619.44  795.095  1994.71
24    409.939736  488.269481   1.76   76.125  332.45  615.395  5762.49
25    426.940071  453.134207   6.09  102.220  370.38  600.850  3600.84
26    487.431370  429.192499   4.74  142.840  437.03  675.520  2303.75

## Soal-5
Carilah waktu terbaik (hari dan jam) dimana paling banyak user gas station melakukan transaksi
---

In [27]:
print(df['Date'].head())
print(df['Date'].dtype)

0    24
1    24
2    24
3    24
4    24
Name: Date, dtype: int32
int32

In [30]:
df = df_transactions.copy()
print(df['Date'].head())
df['Date'] = pd.to_datetime(df['Date'])  # konversi lagi jika masih format string

0    2012-08-24
1    2012-08-24
2    2012-08-24
3    2012-08-24
4    2012-08-24
Name: Date, dtype: object

In [31]:
df['Date'] = pd.to_datetime(df['Date'])
df['Hour'] = pd.to_datetime(df['Time'], format='%H:%M:%S').dt.hour
df_grouped = df.groupby(['Date', 'Hour']).agg({
    'Amount': 'sum', 'Price': 'sum'}).rename(columns={'Price': 'Gas Sales'})
df_grouped

                 Amount  Gas Sales
Date       Hour
2012-08-23 9         79    1785.68
           20        26     720.89
           21        91    1994.71
           22        69    1603.51
           23        31     749.00
...                 ...        ...
2012-08-26 9        310    7146.06
           10       120    2829.68
           11        67    1501.13
           12       152    3428.88
           13        43    1000.70

[61 rows x 2 columns]

In [32]:
df['Date'] = pd.to_datetime(df['Date'])
df['Hour'] = pd.to_datetime(df['Time'], format='%H:%M:%S').dt.hour
df_grouped = df.groupby(['Date', 'Hour']).agg({
    'Amount': 'sum', 'Price': 'sum'}).rename(columns={'Price': 'Gas Sales'})
best_times = df_grouped.reset_index().sort_values(['Date', 'Amount'], ascending=[True, False])
best_per_day = best_times.groupby('Date').first().reset_index()
best_per_day.set_index('Date', inplace=True)
best_per_day

            Hour  Amount  Gas Sales
Date
2012-08-23    21      91    1994.71
2012-08-24    16    1007   23528.20
2012-08-25     9    1034   19362.21
2012-08-26     8     348    7996.20